# Generated by Django 5.1.5 on 2025-02-16 10:58

import firstapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_fathername'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('name', models.CharField(default='mame', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='big_integer_field',
            field=models.BigIntegerField(default=123),
        ),
        migrations.AddField(
            model_name='student',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='char_field',
            field=models.CharField(default='Default Value', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='comma_separated_field',
            field=models.CharField(default='value1,value2,value3', max_length=255, validators=[firstapp.validators.comma_separated_validator]),
        ),
    ]
