# Generated by Django 5.1.5 on 2025-02-16 11:29

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_othermodel_student_big_integer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='date_time_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='student',
            name='email_field',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='float_field',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='student',
            name='json_field',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='many_to_many_field',
            field=models.ManyToManyField(blank=True, to='firstapp.othermodel'),
        ),
        migrations.AddField(
            model_name='student',
            name='null_boolean_field',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='positive_integer_field',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='slug_field',
            field=models.SlugField(default='default-slug'),
        ),
        migrations.AddField(
            model_name='student',
            name='small_integer_field',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='time_field',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='url_field',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='student',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
