# Generated by Django 5.1.5 on 2025-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_student_date_field_student_date_time_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_field',
            field=models.FileField(default='files/default_file.txt', upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='student',
            name='file_path_field',
            field=models.FilePathField(default='/path/to/files/default_file.txt', path='upload/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image_field',
            field=models.ImageField(default='images/default_image.jpg', upload_to='upload/'),
        ),
    ]
