# Generated by Django 5.1.5 on 2025-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_student_file_field_student_file_path_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image_field',
        ),
        migrations.AlterField(
            model_name='student',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
